# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestoid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='reference',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='reference_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='timestamp',
            field=models.CharField(default='0', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(max_length=20),
        ),
    ]
