# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestoid', '0002_auto_20170702_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestoid.Spreadsheet'),
        ),
    ]
